FROM golang:1.17-alpine AS build

WORKDIR /app

# RUN apk update && apk add --no-cache git

COPY go.mod go.sum ./

RUN go mod tidy

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o ./bin/cake-service ./cmd/api

FROM alpine

WORKDIR /app

COPY --from=build /app/bin/cake-service .

CMD [ "/app/cake-service" ]